### ISSUE TITLE
how to serialize std::string object to tpl_map

### ISSUE THREAD

**Issue by stanhome** [troydhanson/tpl#10]
I pack std::string object to tpl_map like this:
    std::string content = readFile();
    char _carray = const_cast<char_>(content.c_str());
    tpl_node *tn = tpl_map("s", carray);
    tpl_pack(tn, 0);
    tpl_dump(tn, TPL_FILE, "player.dat");
    tpl_free(tn);

but it doesn't work.
throw this exception:
![1](https://cloud.githubusercontent.com/assets/7804132/5126173/d2eb4856-7105-11e4-8944-316db834c12a.jpg)
![2](https://cloud.githubusercontent.com/assets/7804132/5126174/d2edce14-7105-11e4-9d71-f2a8334c8f62.jpg)

how can i do it?

**Comment by troydhanson** [comment]
sorry, closing after 3 years
