### ISSUE TITLE
Building TPL in MinGW and using the .a in VS results in linker error

### ISSUE THREAD

**Issue by s2mike** [troydhanson/tpl#16]
TPL is used in a custom library _As Source_ and is compiled along with TPL to .a archive using gcc in MSYS2/MinGW64 environment.

Now this .a file is linked in a Visual C++ Console Project (executable) and the compilation results in the following error

libcustom.a(tpl.o) : error LNK2019: unresolved external symbol __getreent referenced in function tpl_oops
libcustom.a(tpl.o) : error LNK2019: unresolved external symbol __errno referenced in function tpl_gather_blocking

Any idea which other external library should be linked ?

**Comment by troydhanson** [comment]
Hi, unfortunately I do not have a windows with Mingw compilation environment to look into this.

**Comment by s2mike** [comment]
TPL Library was built directly in Visual Studio
