### ISSUE TITLE
memory read overrun in test35

### ISSUE THREAD

**Issue by mlite** [troydhanson/tpl#24]
This is the runtime error msg.

DTS_MSG: Stensal C/C++ DTS detected a fatal program error!
DTS_MSG: Continuing the execution will cause unexpected behaviors, abort!
DTS_MSG: Reading 4 bytes at 0xffffced8 will read undefined values.
DTS_MSG: Diagnostic information:

- The object to-be-read (start:0xffffcecc, size:12 bytes) is allocated at
-     file:/home/sbuilder/workspace/tpl/tests/test35.c::6, 18
-  0xffffcecc               0xffffced7
-  +------------------------+
-  | the object  to-be-read |......
-  +------------------------+
-                            ^~~~~~~~~~
-        the read starts at 0xffffced8 that is right after the object end.
- Stack trace (most recent call first):
-[1]  file:/home/sbuilder/workspace/tpl/tests/test35.c::10, 38
-[2]  file:/musl-1.1.10/src/env/__libc_start_main.c::168, 11

**Comment by troydhanson** [comment]
I believe a6d734c90069cb19fd347c559bcd7e827e688cf9 to test35 fixes this.
