### ISSUE TITLE
Dynamical serialize?

### ISSUE THREAD

**Issue by demonguy** [troydhanson/tpl#26]
Is it possible to dynamical unpack data?
I have a struct like "id:unkown struct". Which means first i need to know the id, then i can now what type of data next and provide corresponding format string.
Is it possible?

**Comment by troydhanson** [comment]
There is something like this in tpl. You can "peek" into the leading parts of a serialized image. Then you can unpack using the correct format string based on what you saw there. There is an example in the [user guide](http://troydhanson.github.io/tpl/userguide.html#tpl_peek), look at Structure peek specifically.

**Comment by demonguy** [comment]
Thanks. That works
