### ISSUE TITLE
Need help: tpl_gather

### ISSUE THREAD

**Issue by DexterMagnific** [troydhanson/tpl#27]
Dear developer,

I need some help regarding the tpl_gather.

We would like to serialize structures of different types through the network. As I understand, the tpl_gather is able to get one tpl at a time (regardless of its type).

Now when the callback is called, the doc says "The callback can do anything with the tpl image but it must not free it.". That's where my understanding stops.

Does that mean that the next step will be a top_load() of the in-memory image argument img ? If so we have a serious problem since we don't know its format string: tpl_load expects a previous call to tpl_map() with the format string.

How do you handle that ?

Thanks

**Comment by troydhanson** [comment]
> On Jun 18, 2019, at 6:25 AM, DexterMagnific <notifications@github.com> wrote:
> 
> Dear developer,
> 
> I need some help regarding the tpl_gather.
> 
> We would like to serialize structures of different types through the network. As I understand, the tpl_gather is able to get one tpl at a time (regardless of its type).
> 
> Now when the callback is called, the doc says "The callback can do anything with the tpl image but it must not free it.". That's where my understanding stops.
> 
> Does that mean that the next step will be a top_load() of the in-memory image argument img ? If so we have a serious problem since we don't know its format string: tpl_load expects a previous call to tpl_map() with the format string.
> 
> How do you handle that ?
> 

Hi, 

You have the right idea. Gather operates on image buffers of unknown format. Once you have an image, you can use tpl_peek to inspect its format prior to loading it. 

Troy

**Comment by DexterMagnific** [comment]
Fantastic ! Did not notice this function. So the tpl format is self describing :)

I have a question regarding format peek: for variable length arrays, is the "variable" attribute returned into the format string or encoded variable length arrays are returned as fixed length array when querying the format string ?

Thanks

**Comment by troydhanson** [comment]
> On Jun 18, 2019, at 4:14 PM, DexterMagnific <notifications@github.com> wrote:
> 
> Fantastic ! Did not notice this function. So the tpl format is self describing :)
> 
Yes, its format is stored in the image itself. 
> I have a question regarding format peek: for variable length arrays, is the "variable" attribute returned into the format string or encoded variable length arrays are returned as fixed length array when querying the format string ?
> 
The variable length arrays like A(i) have a length that can be queried with tpl_Alen once a particular image has been loaded using tpl_load. But the fixed length arrays like i# have lengths that are fixed as part of their format - and these can have their lengths peeked into. There is no conversion between the two kinds of arrays. Hope that helps. 

Troy

**Comment by DexterMagnific** [comment]
Hi,

Thanks a lot.
